- name: Web Server Provisioning
  hosts: localhost

  vars:
   option: started

  tasks:
  - name: debug
    debug:
     msg: "Launched with option: {{option}}"

  - name: Vagrant Provisioning
    module:
     path: 'Vagrantfile'
     state: '{{option}}'
    register: variables
  - debug:
     msg: '{{variables}}'
  - add_host:
     name: pchekhov
     ansible_host: '{{variables.ip}}'
     ansible_port: '{{variables.port}}'
     ansible_user: '{{variables.user}}'
     ansible_connection: 'ssh'
     ansible_ssh_private_key_file: '{{variables.key}}'
    when: variables.status == "running"

- name: Installing software
  hosts: pchekhov
  roles:
  - java
  - java_test
  - tomcat
  - tomcat_test
  - nginx
  - nginx_test
  - deploy
 
