---
- name: check java installation
  command: java -version
  register: java
  ignore_errors: yes

- debug:
    msg: '{{ java.stderr }}'

  when: java.stderr is defined
- name: Java Version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/[^0-9._]//g'
  register: java_version