---
- name: check tomcat's status
  command: systemctl status tomcat
  register: status_tomcat
  become: yes

- debug:
    msg: "{{ status_tomcat.stdout }}"

- name: Check if Tomcat Process Running
  shell: ps -eo cmd | grep -v grep | grep "tomcat"
  args:
    warn: false

- name: Check if Tomcat Responds 200
  shell: curl -sL -w "%{http_code}" localhost:8080 -o /dev/null | grep 200
  args:
    warn: false

- name: Check if It's really Tomcat
  shell: curl -s localhost:8080 | grep '<title>Apache Tomcat' >/dev/null
  args:
    warn: false
